export const homeCarousel = [
  {
    id: 1,
    title: "Fresh Taste, Every Bite 🍽️",
    des: "Discover chef-special dishes made fresh daily",
    image: require("@/assets/all-dammy-image/image-banner-one.jpg"),
  },
  {
    id: 2,
    title: "Exclusive Chef Specials 👨‍🍳",
    des: "Taste premium recipes crafted by top chefs",
    image: require("@/assets/all-dammy-image/image-banner-two.jpg"),
  },
  {
    id: 3,
    title: "Hot Deals on Meals 🔥",
    des: "Enjoy discounts on your favorite restaurant items",
    image: require("@/assets/all-dammy-image/image-banner-three.jpg"),
  },
  {
    id: 4,
    title: "Fast Delivery, Hot Food 🚀",
    des: "Get your favorite meals delivered in minutes",
    image: require("@/assets/all-dammy-image/image-banner-one.jpg"),
  },
];

export const foodCategory = [
  {
    id: 1,
    title: "Burgers",
    image: require("@/assets/all-dammy-image/burgers-01.jpg"),
  },
  {
    id: 2,
    title: "Pizza",
    image: require("@/assets/all-dammy-image/pizza-01.jpg"),
  },
  {
    id: 3,
    title: "Seafood",
    image: require("@/assets/all-dammy-image/seafood-01.jpg"),
  },
  {
    id: 4,
    title: "Desserts",
    image: require("@/assets/all-dammy-image/desserts-01.jpg"),
  },
  {
    id: 5,
    title: "Healthy Food",
    image: require("@/assets/all-dammy-image/healthy-food-01.jpg"),
  },
];

export const restaurantData = [
  {
    id: 1,
    name: "Sub Lover's - Mohakhali",
    category: "Fast Food",
    deliveryTime: "15 min",
    rating: 4.8,
    reviews: "1000+",
    deliveryFee: "$5",
    offer: "Free for first order",
    image: require("@/assets/all-dammy-image/more-food.jpg"),
  },
  {
    id: 2,
    name: "Golden Pizza - Mohakhali",
    category: "Pizza",
    deliveryTime: "15 min",
    rating: 4.8,
    reviews: "2000+",
    deliveryFee: "$4",
    offer: "Free for first order",
    image: require("@/assets/all-dammy-image/healthy-food-03.jpg"),
  },
  {
    id: 3,
    name: "Deshi Bhuna House",
    category: "Bangla Food",
    deliveryTime: "20 min",
    rating: 4.7,
    reviews: "500+",
    deliveryFee: "$3",
    offer: "Free for first order",
    image: require("@/assets/all-dammy-image/image-banner-three.jpg"),
  },
];

export const restaurantAllData = [
  {
    id: "res_01",
    name: "Burger House",
    description: "Juicy burgers with crispy fries & drinks",
    rating: 4.8,
    reviewCount: 512,
    image: require("@/assets/all-dammy-image/burgers-01.jpg"),
    minPrice: "$45",
    numericMinPrice: 45,
    distanceKm: 2.4,
    deliveryTimeMins: 12,
    hasHeart: false,
    badges: ["Best seller", "Free delivery"],
    menu: [
      {
        id: "res_01",
        title: "Cheese Beef Burger",
        price: "$25",
        numericPrice: 25,
        image: require("@/assets/all-dammy-image/burgers-01.jpg"),
      },
    ],
  },

  {
    id: "res_02",
    name: "Sweet Dessert Cafe",
    description: "Fresh cakes, waffles & chocolate desserts",
    rating: 4.7,
    reviewCount: 398,
    image: require("@/assets/all-dammy-image/desserts-01.jpg"),
    minPrice: "$30",
    numericMinPrice: 30,
    distanceKm: 1.8,
    deliveryTimeMins: 10,
    hasHeart: false,
    badges: ["Extra discount"],
    menu: [
      {
        id: "res_02",
        title: "Chocolate Lava Cake",
        price: "$18",
        numericPrice: 18,
        image: require("@/assets/all-dammy-image/desserts-02.jpg"),
      },
    ],
  },

  {
    id: "res_03",
    name: "Healthy Bowl",
    description: "Healthy foods, salads & green meals",
    rating: 4.9,
    reviewCount: 620,
    image: require("@/assets/all-dammy-image/healthy-food-01.jpg"),
    minPrice: "$50",
    numericMinPrice: 50,
    distanceKm: 3.5,
    deliveryTimeMins: 18,
    hasHeart: false,
    badges: ["Healthy choice", "Free delivery"],
    menu: [
      {
        id: "res_03",
        title: "Avocado Salad Bowl",
        price: "$29",
        numericPrice: 29,
        image: require("@/assets/all-dammy-image/healthy-food-02.jpg"),
      },
    ],
  },

  {
    id: "res_04",
    name: "Pizza Corner",
    description: "Hot pizza with extra cheese toppings",
    rating: 4.6,
    reviewCount: 452,
    image: require("@/assets/all-dammy-image/pizza-01.jpg"),
    minPrice: "$55",
    numericMinPrice: 55,
    distanceKm: 4.1,
    deliveryTimeMins: 20,
    hasHeart: false,
    badges: ["Popular", "Combo offer"],
    menu: [
      {
        id: "res_04",
        title: "Pepperoni Pizza",
        price: "$35",
        numericPrice: 35,
        image: require("@/assets/all-dammy-image/pizza-01.jpg"),
      },
    ],
  },

  {
    id: "res_05",
    name: "Ocean Seafood",
    description: "Fresh seafood dishes & grilled fish",
    rating: 4.5,
    reviewCount: 285,
    image: require("@/assets/all-dammy-image/seafood-01.jpg"),
    minPrice: "$60",
    numericMinPrice: 60,
    distanceKm: 5.2,
    deliveryTimeMins: 25,
    hasHeart: false,
    badges: ["Fresh seafood"],
    menu: [
      {
        id: "res_05",
        title: "Grilled Salmon",
        price: "$42",
        numericPrice: 42,
        image: require("@/assets/all-dammy-image/seafood-02.jpg"),
      },
    ],
  },

  {
    id: "res_06",
    name: "Green Life Cafe",
    description: "Organic foods & healthy smoothies",
    rating: 4.8,
    reviewCount: 344,
    image: require("@/assets/all-dammy-image/healthy-food-03.jpg"),
    minPrice: "$42",
    numericMinPrice: 42,
    distanceKm: 2.1,
    deliveryTimeMins: 14,
    hasHeart: false,
    badges: ["Organic", "Free delivery"],
    menu: [
      {
        id: "res_06",
        title: "Fruit Smoothie Bowl",
        price: "$22",
        numericPrice: 22,
        image: require("@/assets/all-dammy-image/healthy-food-04.jpg"),
      },
    ],
  },

  {
    id: "res_07",
    name: "Dessert Kingdom",
    description: "Ice cream, donuts & sweet snacks",
    rating: 4.4,
    reviewCount: 201,
    image: require("@/assets/all-dammy-image/desserts-03.jpg"),
    minPrice: "$28",
    numericMinPrice: 28,
    distanceKm: 1.3,
    deliveryTimeMins: 8,
    hasHeart: false,
    badges: ["Sweet deal"],
    menu: [
      {
        id: "res_07",
        title: "Strawberry Donut",
        price: "$12",
        numericPrice: 12,
        image: require("@/assets/all-dammy-image/desserts-01.jpg"),
      },
    ],
  },

  {
    id: "res_08",
    name: "Sea Breeze",
    description: "Premium seafood platters & sushi",
    rating: 4.7,
    reviewCount: 376,
    image: require("@/assets/all-dammy-image/seafood-03.jpg"),
    minPrice: "$65",
    numericMinPrice: 65,
    distanceKm: 6.4,
    deliveryTimeMins: 28,
    hasHeart: false,
    badges: ["Premium", "Chef special"],
    menu: [
      {
        id: "res_08",
        title: "Seafood Sushi Set",
        price: "$50",
        numericPrice: 50,
        image: require("@/assets/all-dammy-image/seafood-01.jpg"),
      },
    ],
  },

  {
    id: "res_09",
    name: "Fit Meal Hub",
    description: "Protein meals & fitness foods",
    rating: 4.9,
    reviewCount: 540,
    image: require("@/assets/all-dammy-image/healthy-food-05.jpg"),
    minPrice: "$48",
    numericMinPrice: 48,
    distanceKm: 3.1,
    deliveryTimeMins: 16,
    hasHeart: false,
    badges: ["Gym favorite"],
    menu: [
      {
        id: "res_09",
        title: "Chicken Protein Bowl",
        price: "$31",
        numericPrice: 31,
        image: require("@/assets/all-dammy-image/healthy-food-06.jpg"),
      },
    ],
  },

  {
    id: "res_10",
    name: "Italian Pizza Spot",
    description: "Authentic Italian pizza & pasta",
    rating: 4.6,
    reviewCount: 467,
    image: require("@/assets/all-dammy-image/pizza-01.jpg"),
    minPrice: "$58",
    numericMinPrice: 58,
    distanceKm: 4.9,
    deliveryTimeMins: 22,
    hasHeart: false,
    badges: ["Italian taste"],
    menu: [
      {
        id: "res_10",
        title: "Classic Margherita",
        price: "$30",
        numericPrice: 30,
        image: require("@/assets/all-dammy-image/pizza-01.jpg"),
      },
    ],
  },
];
